/**
 * Centralized Schedule Data
 * All dance classes aggregated for the ScheduleSection component
 */

export type DayKey =
  | 'monday'
  | 'tuesday'
  | 'wednesday'
  | 'thursday'
  | 'friday'
  | 'saturday'
  | 'sunday';

export type CategoryKey = 'latino' | 'urbano' | 'danza' | 'fitness';

export type LevelKey =
  | 'beginner'
  | 'basic'
  | 'intermediate'
  | 'advanced'
  | 'all'
  | 'intermediateAdvanced';

export interface ScheduleClass {
  id: string;
  styleName: string;
  className: string;
  day: DayKey;
  time: string;
  teacher: string;
  level: LevelKey;
  category: CategoryKey;
  /** Link to the class page */
  link?: string;
}

// Day order for sorting
export const DAY_ORDER: DayKey[] = [
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
  'sunday',
];

// Category colors for visual distinction
export const CATEGORY_COLORS: Record<CategoryKey, string> = {
  latino: 'amber',
  urbano: 'rose',
  danza: 'emerald',
  fitness: 'sky',
};

// All schedule data - sorted by time within each day
export const SCHEDULE_DATA: ScheduleClass[] = [
  // ========== MONDAY ==========
  // Mañanas
  {
    id: 'mon-1',
    styleName: 'Sexy Reggaeton',
    className: 'Sexy Reggaeton Principiantes',
    day: 'monday',
    time: '11:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/sexy-reggaeton-barcelona',
  },
  {
    id: 'mon-2',
    styleName: 'Contemporáneo',
    className: 'Contemporáneo Lírico Básico',
    day: 'monday',
    time: '11:00',
    teacher: 'Alejandro Miñoso',
    level: 'basic',
    category: 'danza',
    link: '/clases/contemporaneo-barcelona',
  },
  {
    id: 'mon-3',
    styleName: 'Sexy Style',
    className: 'Sexy Style Principiantes',
    day: 'monday',
    time: '12:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/sexy-style-barcelona',
  },
  {
    id: 'mon-4',
    styleName: 'Stretching',
    className: 'Stretching Principiantes',
    day: 'monday',
    time: '12:00',
    teacher: 'Alejandro Miñoso',
    level: 'beginner',
    category: 'fitness',
    link: '/clases/stretching-barcelona',
  },
  // Tardes/Noches
  {
    id: 'mon-5',
    styleName: 'Sexy Reggaeton',
    className: 'Sexy Reggaeton Principiantes',
    day: 'monday',
    time: '18:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/sexy-reggaeton-barcelona',
  },
  {
    id: 'mon-6',
    styleName: 'Stretching',
    className: 'Stretching Principiantes',
    day: 'monday',
    time: '18:00',
    teacher: 'Cristina Aliaga',
    level: 'beginner',
    category: 'fitness',
    link: '/clases/stretching-barcelona',
  },
  {
    id: 'mon-7',
    styleName: 'Twerk',
    className: 'Twerk Básico',
    day: 'monday',
    time: '18:00',
    teacher: 'Sandra Gomez',
    level: 'basic',
    category: 'urbano',
    link: '/clases/twerk-barcelona',
  },
  {
    id: 'mon-8',
    styleName: 'Contemporáneo',
    className: 'Contemporáneo Lírico Básico',
    day: 'monday',
    time: '19:00',
    teacher: 'Daniel Sené',
    level: 'basic',
    category: 'danza',
    link: '/clases/contemporaneo-barcelona',
  },
  {
    id: 'mon-9',
    styleName: 'Salsa Ladies Styling',
    className: 'Salsa Cubana Ladies Styling Intermedio',
    day: 'monday',
    time: '19:00',
    teacher: 'Yunaisy Farray',
    level: 'intermediate',
    category: 'latino',
    link: '/clases/salsa-lady-style-barcelona',
  },
  {
    id: 'mon-10',
    styleName: 'Sexy Style',
    className: 'Sexy Style Intermedio/Avanzado',
    day: 'monday',
    time: '19:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'intermediateAdvanced',
    category: 'urbano',
    link: '/clases/sexy-style-barcelona',
  },
  {
    id: 'mon-11',
    styleName: 'Body Conditioning',
    className: 'Body Conditioning & Stretching Open Level',
    day: 'monday',
    time: '19:00',
    teacher: 'Cristina Aliaga',
    level: 'all',
    category: 'fitness',
    link: '/clases/stretching-barcelona',
  },
  {
    id: 'mon-12',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana Avanzado',
    day: 'monday',
    time: '20:00',
    teacher: 'Yunaisy Farray & Iroel Bastarreche',
    level: 'advanced',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'mon-13',
    styleName: 'Ballet',
    className: 'Ballet Clásico Intermedio',
    day: 'monday',
    time: '20:00',
    teacher: 'Daniel Sené',
    level: 'intermediate',
    category: 'danza',
    link: '/clases/ballet-barcelona',
  },
  {
    id: 'mon-14',
    styleName: 'Sexy Style',
    className: 'Sexy Style Básico',
    day: 'monday',
    time: '20:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'basic',
    category: 'urbano',
    link: '/clases/sexy-style-barcelona',
  },
  {
    id: 'mon-15',
    styleName: 'Bum Bum',
    className: 'Bum Bum Cuerpo Fit Open Level',
    day: 'monday',
    time: '20:00',
    teacher: 'Cristina Aliaga',
    level: 'all',
    category: 'fitness',
    link: '/clases/bum-bum-gluteos-barcelona',
  },
  {
    id: 'mon-16',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana Básico I',
    day: 'monday',
    time: '21:00',
    teacher: 'Yunaisy Farray & Iroel Bastarreche',
    level: 'basic',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'mon-17',
    styleName: 'Afro Contemporáneo',
    className: 'Afro Contemporáneo Básico',
    day: 'monday',
    time: '21:00',
    teacher: 'Charlie Breezy',
    level: 'basic',
    category: 'danza',
    link: '/clases/afro-contemporaneo-barcelona',
  },
  {
    id: 'mon-18',
    styleName: 'Sexy Reggaeton',
    className: 'Sexy Reggaeton Básico',
    day: 'monday',
    time: '21:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'basic',
    category: 'urbano',
    link: '/clases/sexy-reggaeton-barcelona',
  },
  {
    id: 'mon-19',
    styleName: 'Stretching',
    className: 'Stretching Backbending & Legs Avanzado',
    day: 'monday',
    time: '21:00',
    teacher: 'Cristina Aliaga',
    level: 'advanced',
    category: 'fitness',
    link: '/clases/stretching-barcelona',
  },
  {
    id: 'mon-20',
    styleName: 'Bachata',
    className: 'Bachata Básico',
    day: 'monday',
    time: '22:00',
    teacher: 'Mathias Font & Eugenia Trujillo',
    level: 'basic',
    category: 'latino',
    link: '/clases/bachata-barcelona',
  },
  {
    id: 'mon-21',
    styleName: 'Hip Hop Reggaeton',
    className: 'Hip Hop Reggaeton Básico',
    day: 'monday',
    time: '22:00',
    teacher: 'Charlie Breezy',
    level: 'basic',
    category: 'urbano',
    link: '/clases/hip-hop-reggaeton-barcelona',
  },
  {
    id: 'mon-22',
    styleName: 'Dancehall',
    className: 'Dancehall Principiantes',
    day: 'monday',
    time: '22:00',
    teacher: 'Sandra Gomez',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/dancehall-barcelona',
  },

  // ========== TUESDAY ==========
  // Tardes/Noches
  {
    id: 'tue-1',
    styleName: 'Sexy Style',
    className: 'Sexy Style Básico',
    day: 'tuesday',
    time: '18:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'basic',
    category: 'urbano',
    link: '/clases/sexy-style-barcelona',
  },
  {
    id: 'tue-2',
    styleName: 'Modern Jazz',
    className: 'Modern Jazz Principiantes',
    day: 'tuesday',
    time: '18:00',
    teacher: 'Alejandro Miñoso',
    level: 'beginner',
    category: 'danza',
    link: '/clases/modern-jazz-barcelona',
  },
  {
    id: 'tue-3',
    styleName: 'Afrobeats',
    className: 'Afrobeats "Ntcham" Básico',
    day: 'tuesday',
    time: '18:00',
    teacher: 'May Barleycorn',
    level: 'basic',
    category: 'urbano',
    link: '/clases/afrobeat-barcelona',
  },
  {
    id: 'tue-4',
    styleName: 'Hip Hop Reggaeton',
    className: 'Hip Hop Reggaeton Principiantes',
    day: 'tuesday',
    time: '18:00',
    teacher: 'Charlie Breezy',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/hip-hop-reggaeton-barcelona',
  },
  {
    id: 'tue-5',
    styleName: 'Afro Contemporáneo',
    className: 'Afro Contemporáneo Intermedio/Avanzado',
    day: 'tuesday',
    time: '19:00',
    teacher: 'Yunaisy Farray',
    level: 'intermediateAdvanced',
    category: 'danza',
    link: '/clases/afro-contemporaneo-barcelona',
  },
  {
    id: 'tue-6',
    styleName: 'Bachata',
    className: 'Bachata Principiantes',
    day: 'tuesday',
    time: '19:00',
    teacher: 'Mathias Font & Eugenia Trujillo',
    level: 'beginner',
    category: 'latino',
    link: '/clases/bachata-barcelona',
  },
  {
    id: 'tue-7',
    styleName: 'Reggaeton Cubano',
    className: 'Reggaeton Cubano (Reparto) Open Level',
    day: 'tuesday',
    time: '19:00',
    teacher: 'Charlie Breezy',
    level: 'all',
    category: 'urbano',
    link: '/clases/reggaeton-cubano-barcelona',
  },
  {
    id: 'tue-8',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana Básico II',
    day: 'tuesday',
    time: '19:00',
    teacher: 'Iroel Bastarreche',
    level: 'basic',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'tue-9',
    styleName: 'Sexy Reggaeton',
    className: 'Sexy Reggaeton Principiantes',
    day: 'tuesday',
    time: '20:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/sexy-reggaeton-barcelona',
  },
  {
    id: 'tue-10',
    styleName: 'Bachata',
    className: 'Bachata Intermedio',
    day: 'tuesday',
    time: '20:00',
    teacher: 'Eugenia Trujillo & Mathias Font',
    level: 'intermediate',
    category: 'latino',
    link: '/clases/bachata-barcelona',
  },
  {
    id: 'tue-11',
    styleName: 'Femmology',
    className: 'Femmology Heels Technique Intermedio',
    day: 'tuesday',
    time: '20:30',
    teacher: 'Yunaisy Farray',
    level: 'intermediate',
    category: 'urbano',
    link: '/clases/femmology-barcelona',
  },
  {
    id: 'tue-12',
    styleName: 'Folklore Cubano',
    className: 'Folklore Cubano Open Level',
    day: 'tuesday',
    time: '20:30',
    teacher: 'Greechen Mendez',
    level: 'all',
    category: 'latino',
    link: '/clases/folklore-cubano-barcelona',
  },
  {
    id: 'tue-13',
    styleName: 'Sexy Style',
    className: 'Sexy Style Principiantes',
    day: 'tuesday',
    time: '21:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/sexy-style-barcelona',
  },
  {
    id: 'tue-14',
    styleName: 'Bachata',
    className: 'Bachata Avanzado',
    day: 'tuesday',
    time: '21:30',
    teacher: 'Mathias Font & Eugenia Trujillo',
    level: 'advanced',
    category: 'latino',
    link: '/clases/bachata-barcelona',
  },
  {
    id: 'tue-15',
    styleName: 'Femmology',
    className: 'Femmology Heels Technique Avanzado',
    day: 'tuesday',
    time: '21:30',
    teacher: 'Yunaisy Farray',
    level: 'advanced',
    category: 'urbano',
    link: '/clases/femmology-barcelona',
  },
  {
    id: 'tue-16',
    styleName: 'Timba',
    className: 'Timba Cubana Básico',
    day: 'tuesday',
    time: '21:30',
    teacher: 'Greechen Mendez',
    level: 'basic',
    category: 'latino',
    link: '/clases/timba-barcelona',
  },
  {
    id: 'tue-17',
    styleName: 'Twerk',
    className: 'Twerk Básico',
    day: 'tuesday',
    time: '22:00',
    teacher: 'Sandra Gomez',
    level: 'basic',
    category: 'urbano',
    link: '/clases/twerk-barcelona',
  },

  // ========== WEDNESDAY ==========
  // Mañanas
  {
    id: 'wed-1',
    styleName: 'Salsa Ladies Styling',
    className: 'Salsa Cubana Ladies Styling Principiantes',
    day: 'wednesday',
    time: '11:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'beginner',
    category: 'latino',
    link: '/clases/salsa-lady-style-barcelona',
  },
  {
    id: 'wed-2',
    styleName: 'Contemporáneo',
    className: 'Contemporáneo Suelo & Flow Básico/Intermedio',
    day: 'wednesday',
    time: '11:00',
    teacher: 'Alejandro Miñoso',
    level: 'intermediate',
    category: 'danza',
    link: '/clases/contemporaneo-barcelona',
  },
  {
    id: 'wed-3',
    styleName: 'Afro Jazz',
    className: 'Afro Jazz Principiantes',
    day: 'wednesday',
    time: '12:00',
    teacher: 'Alejandro Miñoso',
    level: 'beginner',
    category: 'danza',
    link: '/clases/afro-jazz-barcelona',
  },
  {
    id: 'wed-4',
    styleName: 'Dancehall',
    className: 'Dancehall Female Principiantes',
    day: 'wednesday',
    time: '12:00',
    teacher: 'Isa López',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/dancehall-barcelona',
  },
  // Tardes/Noches
  {
    id: 'wed-5',
    styleName: 'Stretching',
    className: 'Stretching Principiantes',
    day: 'wednesday',
    time: '18:00',
    teacher: 'Cristina Aliaga',
    level: 'beginner',
    category: 'fitness',
    link: '/clases/stretching-barcelona',
  },
  {
    id: 'wed-6',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana Intermedio II',
    day: 'wednesday',
    time: '18:00',
    teacher: 'Iroel Bastarreche',
    level: 'intermediate',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'wed-7',
    styleName: 'Afrobeats',
    className: 'Afrobeats Principiantes',
    day: 'wednesday',
    time: '18:00',
    teacher: 'Charlie Breezy',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/afrobeat-barcelona',
  },
  {
    id: 'wed-8',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana Intermedio I',
    day: 'wednesday',
    time: '19:00',
    teacher: 'Iroel Bastarreche',
    level: 'intermediate',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'wed-9',
    styleName: 'Salsa Ladies Styling',
    className: 'Salsa Cubana Ladies Styling Básico',
    day: 'wednesday',
    time: '19:00',
    teacher: 'Yunaisy Farray',
    level: 'basic',
    category: 'latino',
    link: '/clases/salsa-lady-style-barcelona',
  },
  {
    id: 'wed-10',
    styleName: 'Hip Hop Reggaeton',
    className: 'Hip Hop Reggaeton Intermedio/Avanzado',
    day: 'wednesday',
    time: '19:00',
    teacher: 'Charlie Breezy',
    level: 'intermediateAdvanced',
    category: 'urbano',
    link: '/clases/hip-hop-reggaeton-barcelona',
  },
  {
    id: 'wed-11',
    styleName: 'Bum Bum',
    className: 'Bum Bum Glúteos Maravillosos Open Level',
    day: 'wednesday',
    time: '19:00',
    teacher: 'Cristina Aliaga',
    level: 'all',
    category: 'fitness',
    link: '/clases/bum-bum-gluteos-barcelona',
  },
  {
    id: 'wed-12',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana Principiantes',
    day: 'wednesday',
    time: '20:00',
    teacher: 'Iroel Bastarreche',
    level: 'beginner',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'wed-13',
    styleName: 'Salsa Ladies Styling',
    className: 'Salsa Cubana Ladies Styling Principiantes',
    day: 'wednesday',
    time: '20:00',
    teacher: 'Lía Valdes',
    level: 'beginner',
    category: 'latino',
    link: '/clases/salsa-lady-style-barcelona',
  },
  {
    id: 'wed-14',
    styleName: 'Contemporáneo',
    className: 'Contemporáneo Lírico Intermedio',
    day: 'wednesday',
    time: '20:00',
    teacher: 'Daniel Sené',
    level: 'intermediate',
    category: 'danza',
    link: '/clases/contemporaneo-barcelona',
  },
  {
    id: 'wed-15',
    styleName: 'Stretching',
    className: 'Stretching Backbending & Legs Intermedio',
    day: 'wednesday',
    time: '20:00',
    teacher: 'Cristina Aliaga',
    level: 'intermediate',
    category: 'fitness',
    link: '/clases/stretching-barcelona',
  },
  {
    id: 'wed-16',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana Principiantes',
    day: 'wednesday',
    time: '21:00',
    teacher: 'Iroel Bastarreche',
    level: 'beginner',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'wed-17',
    styleName: 'Femmology',
    className: 'Femmology Heels Technique Básico',
    day: 'wednesday',
    time: '21:00',
    teacher: 'Yunaisy Farray',
    level: 'basic',
    category: 'urbano',
    link: '/clases/femmology-barcelona',
  },
  {
    id: 'wed-18',
    styleName: 'Dancehall',
    className: 'Dancehall Twerk Intermedio',
    day: 'wednesday',
    time: '21:00',
    teacher: 'Isa López',
    level: 'intermediate',
    category: 'urbano',
    link: '/clases/dancehall-barcelona',
  },
  {
    id: 'wed-19',
    styleName: 'Twerk',
    className: 'Twerk Intermedio',
    day: 'wednesday',
    time: '22:00',
    teacher: 'Sandra Gomez',
    level: 'intermediate',
    category: 'urbano',
    link: '/clases/twerk-barcelona',
  },

  // ========== THURSDAY ==========
  // Mañanas
  {
    id: 'thu-1',
    styleName: 'Sexy Reggaeton',
    className: 'Sexy Reggaeton Open Level',
    day: 'thursday',
    time: '10:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'all',
    category: 'urbano',
    link: '/clases/sexy-reggaeton-barcelona',
  },
  {
    id: 'thu-2',
    styleName: 'Reggaeton',
    className: 'Reggaeton Principiantes',
    day: 'thursday',
    time: '10:00',
    teacher: 'Alejandro Miñoso',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/reggaeton-cubano-barcelona',
  },
  {
    id: 'thu-3',
    styleName: 'Sexy Style',
    className: 'Sexy Style Principiantes',
    day: 'thursday',
    time: '11:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/sexy-style-barcelona',
  },
  {
    id: 'thu-4',
    styleName: 'Ballet',
    className: 'Ballet Principiantes',
    day: 'thursday',
    time: '11:00',
    teacher: 'Alejandro Miñoso',
    level: 'beginner',
    category: 'danza',
    link: '/clases/ballet-barcelona',
  },
  {
    id: 'thu-5',
    styleName: 'Twerk',
    className: 'Twerk Principiantes',
    day: 'thursday',
    time: '11:00',
    teacher: 'Isa López',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/twerk-barcelona',
  },
  // Tardes/Noches
  {
    id: 'thu-6',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana Básico I',
    day: 'thursday',
    time: '18:00',
    teacher: 'Iroel Bastarreche',
    level: 'basic',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'thu-7',
    styleName: 'Contemporáneo',
    className: 'Contemporáneo Lírico Principiantes',
    day: 'thursday',
    time: '18:00',
    teacher: 'Daniel Sené',
    level: 'beginner',
    category: 'danza',
    link: '/clases/contemporaneo-barcelona',
  },
  {
    id: 'thu-8',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana Intermedio II',
    day: 'thursday',
    time: '19:00',
    teacher: 'Iroel Bastarreche',
    level: 'intermediate',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'thu-9',
    styleName: 'Sexy Reggaeton',
    className: 'Sexy Reggaeton Intermedio',
    day: 'thursday',
    time: '19:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'intermediate',
    category: 'urbano',
    link: '/clases/sexy-reggaeton-barcelona',
  },
  {
    id: 'thu-10',
    styleName: 'Afro Jazz',
    className: 'Afro Jazz Intermedio/Avanzado',
    day: 'thursday',
    time: '19:00',
    teacher: 'Yunaisy Farray',
    level: 'intermediateAdvanced',
    category: 'danza',
    link: '/clases/afro-jazz-barcelona',
  },
  {
    id: 'thu-11',
    styleName: 'Stretching',
    className: 'Stretching Principiantes',
    day: 'thursday',
    time: '19:00',
    teacher: 'Daniel Sené',
    level: 'beginner',
    category: 'fitness',
    link: '/clases/stretching-barcelona',
  },
  {
    id: 'thu-12',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana Intermedio III',
    day: 'thursday',
    time: '20:00',
    teacher: 'Iroel Bastarreche & Yasmina Fernández',
    level: 'intermediate',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'thu-13',
    styleName: 'Bachata',
    className: 'Bachata Principiantes',
    day: 'thursday',
    time: '20:00',
    teacher: 'Carlos & Noemi',
    level: 'beginner',
    category: 'latino',
    link: '/clases/bachata-barcelona',
  },
  {
    id: 'thu-14',
    styleName: 'Hip Hop',
    className: 'Hip Hop Urbano Open Level',
    day: 'thursday',
    time: '20:00',
    teacher: 'Marcos Martínez',
    level: 'all',
    category: 'urbano',
    link: '/clases/hip-hop-barcelona',
  },
  {
    id: 'thu-15',
    styleName: 'Timba',
    className: 'Salsa Ladies Styling Timba Fusión Intermedio/Avanzado',
    day: 'thursday',
    time: '20:30',
    teacher: 'Yunaisy Farray',
    level: 'intermediateAdvanced',
    category: 'latino',
    link: '/clases/timba-barcelona',
  },
  {
    id: 'thu-16',
    styleName: 'Bachata',
    className: 'Bachata Lady Style Open Level',
    day: 'thursday',
    time: '21:00',
    teacher: 'Eugenia Trujillo',
    level: 'all',
    category: 'latino',
    link: '/clases/bachata-barcelona',
  },
  {
    id: 'thu-17',
    styleName: 'Sexy Style',
    className: 'Sexy Style Intermedio',
    day: 'thursday',
    time: '21:00',
    teacher: 'Yasmina Fernández Ruiz',
    level: 'intermediate',
    category: 'urbano',
    link: '/clases/sexy-style-barcelona',
  },
  {
    id: 'thu-18',
    styleName: 'Dancehall',
    className: 'Dancehall Female Principiantes',
    day: 'thursday',
    time: '21:00',
    teacher: 'Isa López',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/dancehall-barcelona',
  },
  {
    id: 'thu-19',
    styleName: 'Dancehall',
    className: 'Dancehall Female Intermedio',
    day: 'thursday',
    time: '21:00',
    teacher: 'Isa López',
    level: 'intermediate',
    category: 'urbano',
    link: '/clases/dancehall-barcelona',
  },
  {
    id: 'thu-20',
    styleName: 'Femmology',
    className: 'Femmology Heels Technique Principiantes',
    day: 'thursday',
    time: '21:30',
    teacher: 'Yunaisy Farray',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/femmology-barcelona',
  },
  {
    id: 'thu-21',
    styleName: 'Bachata',
    className: 'Bachata Principiantes',
    day: 'thursday',
    time: '22:00',
    teacher: 'Carlos & Noemi',
    level: 'beginner',
    category: 'latino',
    link: '/clases/bachata-barcelona',
  },
  {
    id: 'thu-22',
    styleName: 'Dancehall',
    className: 'Dancehall Básico',
    day: 'thursday',
    time: '22:00',
    teacher: 'Sandra Gomez',
    level: 'basic',
    category: 'urbano',
    link: '/clases/dancehall-barcelona',
  },

  // ========== FRIDAY ==========
  // Tardes/Noches
  {
    id: 'fri-1',
    styleName: 'Dancehall',
    className: 'Dancehall Twerk Principiantes',
    day: 'friday',
    time: '18:00',
    teacher: 'Isa López',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/dancehall-barcelona',
  },
  {
    id: 'fri-2',
    styleName: 'Afrobeats',
    className: 'Afrobeats Básico',
    day: 'friday',
    time: '18:00',
    teacher: 'Charlie Breezy',
    level: 'basic',
    category: 'urbano',
    link: '/clases/afrobeat-barcelona',
  },
  {
    id: 'fri-3',
    styleName: 'Hip Hop Reggaeton',
    className: 'Hip Hop Reggaeton Principiantes',
    day: 'friday',
    time: '19:00',
    teacher: 'Charlie Breezy',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/hip-hop-reggaeton-barcelona',
  },
  {
    id: 'fri-4',
    styleName: 'Timba',
    className: 'Salsa Ladies Styling Timba Fusión Básico',
    day: 'friday',
    time: '19:00',
    teacher: 'Lía Valdes',
    level: 'basic',
    category: 'latino',
    link: '/clases/timba-barcelona',
  },
  {
    id: 'fri-5',
    styleName: 'Bachata',
    className: 'Bachata Intermedio',
    day: 'friday',
    time: '19:00',
    teacher: 'Eugenia Trujillo & Juanes',
    level: 'intermediate',
    category: 'latino',
    link: '/clases/bachata-barcelona',
  },
  {
    id: 'fri-6',
    styleName: 'Dancehall',
    className: 'Dancehall Female Principiantes',
    day: 'friday',
    time: '19:00',
    teacher: 'Isa López',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/dancehall-barcelona',
  },
  {
    id: 'fri-7',
    styleName: 'Twerk',
    className: 'Twerk Principiantes',
    day: 'friday',
    time: '19:00',
    teacher: 'Isa López',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/twerk-barcelona',
  },
];

// Helper function to get classes by day
export const getClassesByDay = (day: DayKey): ScheduleClass[] => {
  return SCHEDULE_DATA.filter(c => c.day === day).sort((a, b) => a.time.localeCompare(b.time));
};

// Helper function to get classes by category
export const getClassesByCategory = (category: CategoryKey): ScheduleClass[] => {
  return SCHEDULE_DATA.filter(c => c.category === category);
};

// Helper function to filter classes
export const filterClasses = (
  day: DayKey | 'all',
  category: CategoryKey | 'all',
  level: LevelKey | 'all' = 'all'
): ScheduleClass[] => {
  let filtered = [...SCHEDULE_DATA];

  if (day !== 'all') {
    filtered = filtered.filter(c => c.day === day);
  }

  if (category !== 'all') {
    filtered = filtered.filter(c => c.category === category);
  }

  if (level !== 'all') {
    filtered = filtered.filter(c => c.level === level);
  }

  return filtered.sort((a, b) => {
    // Sort by day first, then by time
    const dayDiff = DAY_ORDER.indexOf(a.day) - DAY_ORDER.indexOf(b.day);
    if (dayDiff !== 0) return dayDiff;
    return a.time.localeCompare(b.time);
  });
};

// Get class count by level
export const getCountByLevel = (): Record<LevelKey | 'all', number> => {
  return {
    all: SCHEDULE_DATA.length,
    beginner: SCHEDULE_DATA.filter(c => c.level === 'beginner').length,
    basic: SCHEDULE_DATA.filter(c => c.level === 'basic').length,
    intermediate: SCHEDULE_DATA.filter(c => c.level === 'intermediate').length,
    advanced: SCHEDULE_DATA.filter(c => c.level === 'advanced').length,
    intermediateAdvanced: SCHEDULE_DATA.filter(c => c.level === 'intermediateAdvanced').length,
  };
};

// Get unique teachers
export const getUniqueTeachers = (): string[] => {
  return [...new Set(SCHEDULE_DATA.map(c => c.teacher))].sort();
};

// Get class count by category
export const getCountByCategory = (): Record<CategoryKey | 'all', number> => {
  return {
    all: SCHEDULE_DATA.length,
    latino: getClassesByCategory('latino').length,
    urbano: getClassesByCategory('urbano').length,
    danza: getClassesByCategory('danza').length,
    fitness: getClassesByCategory('fitness').length,
  };
};
