/**
 * Centralized Schedule Data
 * All dance classes aggregated for the ScheduleSection component
 */

export type DayKey =
  | 'monday'
  | 'tuesday'
  | 'wednesday'
  | 'thursday'
  | 'friday'
  | 'saturday'
  | 'sunday';

export type CategoryKey = 'latino' | 'urbano' | 'danza' | 'fitness';

export type LevelKey =
  | 'beginner'
  | 'basic'
  | 'intermediate'
  | 'advanced'
  | 'all'
  | 'intermediateAdvanced';

export interface ScheduleClass {
  id: string;
  styleName: string;
  className: string;
  day: DayKey;
  time: string;
  teacher: string;
  level: LevelKey;
  category: CategoryKey;
  /** Link to the class page */
  link?: string;
}

// Day order for sorting
export const DAY_ORDER: DayKey[] = [
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
  'sunday',
];

// Category colors for visual distinction
export const CATEGORY_COLORS: Record<CategoryKey, string> = {
  latino: 'amber',
  urbano: 'rose',
  danza: 'emerald',
  fitness: 'sky',
};

// All schedule data - sorted by time within each day
export const SCHEDULE_DATA: ScheduleClass[] = [
  // ========== MONDAY ==========
  {
    id: 'mon-1',
    styleName: 'Sexy Reggaeton',
    className: 'Sexy Reggaeton',
    day: 'monday',
    time: '11:00',
    teacher: 'Yasmina Fernández',
    level: 'basic',
    category: 'urbano',
    link: '/clases/sexy-reggaeton-barcelona',
  },
  {
    id: 'mon-2',
    styleName: 'Contemporáneo',
    className: 'Contemporáneo Lírico',
    day: 'monday',
    time: '11:00',
    teacher: 'Alejandro Miñoso',
    level: 'basic',
    category: 'danza',
    link: '/clases/contemporaneo-barcelona',
  },
  {
    id: 'mon-3',
    styleName: 'Stretching',
    className: 'Stretching',
    day: 'monday',
    time: '18:00',
    teacher: 'Cris Ag',
    level: 'beginner',
    category: 'fitness',
    link: '/clases/stretching-barcelona',
  },
  {
    id: 'mon-4',
    styleName: 'Sexy Reggaeton',
    className: 'Sexy Reggaeton',
    day: 'monday',
    time: '18:00',
    teacher: 'Yasmina Fernández',
    level: 'basic',
    category: 'urbano',
    link: '/clases/sexy-reggaeton-barcelona',
  },
  {
    id: 'mon-5',
    styleName: 'Twerk',
    className: 'Twerk',
    day: 'monday',
    time: '18:00',
    teacher: 'Sandra Gómez',
    level: 'basic',
    category: 'urbano',
    link: '/clases/twerk-barcelona',
  },
  {
    id: 'mon-6',
    styleName: 'Contemporáneo',
    className: 'Contemporáneo Lírico',
    day: 'monday',
    time: '19:00',
    teacher: 'Daniel Sené',
    level: 'basic',
    category: 'danza',
    link: '/clases/contemporaneo-barcelona',
  },
  {
    id: 'mon-7',
    styleName: 'Salsa Lady Style',
    className: 'Salsa Lady Style',
    day: 'monday',
    time: '19:00',
    teacher: 'Yunaisy Farray',
    level: 'basic',
    category: 'latino',
    link: '/clases/salsa-lady-style-barcelona',
  },
  {
    id: 'mon-8',
    styleName: 'Sexy Style',
    className: 'Sexy Style',
    day: 'monday',
    time: '19:00',
    teacher: 'Yasmina Fernández',
    level: 'intermediateAdvanced',
    category: 'urbano',
    link: '/clases/sexy-style-barcelona',
  },
  {
    id: 'mon-9',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana Nivel 0',
    day: 'monday',
    time: '20:00',
    teacher: 'Yunaisy Farray',
    level: 'beginner',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'mon-10',
    styleName: 'Ballet',
    className: 'Ballet',
    day: 'monday',
    time: '20:00',
    teacher: 'Daniel Sené',
    level: 'intermediate',
    category: 'danza',
    link: '/clases/ballet-barcelona',
  },
  {
    id: 'mon-11',
    styleName: 'Sexy Style',
    className: 'Sexy Style',
    day: 'monday',
    time: '20:00',
    teacher: 'Yasmina Fernández',
    level: 'basic',
    category: 'urbano',
    link: '/clases/sexy-style-barcelona',
  },
  {
    id: 'mon-12',
    styleName: 'Afro Contemporáneo',
    className: 'Afro Contemporáneo',
    day: 'monday',
    time: '21:00',
    teacher: 'Charlie Breezy',
    level: 'basic',
    category: 'danza',
    link: '/clases/afro-contemporaneo-barcelona',
  },
  {
    id: 'mon-13',
    styleName: 'Sexy Reggaeton',
    className: 'Sexy Reggaeton',
    day: 'monday',
    time: '21:00',
    teacher: 'Yasmina Fernández',
    level: 'basic',
    category: 'urbano',
    link: '/clases/sexy-reggaeton-barcelona',
  },
  {
    id: 'mon-14',
    styleName: 'Stretching',
    className: 'Backbending & Legs',
    day: 'monday',
    time: '21:00',
    teacher: 'Cris Ag',
    level: 'intermediateAdvanced',
    category: 'fitness',
    link: '/clases/stretching-barcelona',
  },
  {
    id: 'mon-15',
    styleName: 'Hip Hop Reggaeton',
    className: 'Hip Hop Reggaeton',
    day: 'monday',
    time: '22:00',
    teacher: 'Charlie Breezy',
    level: 'basic',
    category: 'urbano',
    link: '/clases/hip-hop-reggaeton-barcelona',
  },
  {
    id: 'mon-16',
    styleName: 'Dancehall',
    className: 'Dancehall Female',
    day: 'monday',
    time: '22:00',
    teacher: 'Sandra Gómez',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/dancehall-barcelona',
  },

  // ========== TUESDAY ==========
  {
    id: 'tue-1',
    styleName: 'Hip Hop Reggaeton',
    className: 'Hip Hop Reggaeton',
    day: 'tuesday',
    time: '18:00',
    teacher: 'Charlie Breezy',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/hip-hop-reggaeton-barcelona',
  },
  {
    id: 'tue-2',
    styleName: 'Modern Jazz',
    className: 'Modern Jazz',
    day: 'tuesday',
    time: '18:00',
    teacher: 'Alejandro Miñoso',
    level: 'basic',
    category: 'danza',
    link: '/clases/modern-jazz-barcelona',
  },
  {
    id: 'tue-3',
    styleName: 'Sexy Style',
    className: 'Sexy Style',
    day: 'tuesday',
    time: '18:00',
    teacher: 'Yasmina Fernández',
    level: 'basic',
    category: 'urbano',
    link: '/clases/sexy-style-barcelona',
  },
  {
    id: 'tue-4',
    styleName: 'Afrobeat',
    className: 'Afrobeat',
    day: 'tuesday',
    time: '18:00',
    teacher: 'Redblueh',
    level: 'basic',
    category: 'urbano',
    link: '/clases/afrobeat-barcelona',
  },
  {
    id: 'tue-5',
    styleName: 'Afro Contemporáneo',
    className: 'Afro Contemporáneo',
    day: 'tuesday',
    time: '19:00',
    teacher: 'Yunaisy Farray',
    level: 'intermediateAdvanced',
    category: 'danza',
    link: '/clases/afro-contemporaneo-barcelona',
  },
  {
    id: 'tue-6',
    styleName: 'Reggaeton Cubano',
    className: 'Reggaeton Cubano',
    day: 'tuesday',
    time: '19:00',
    teacher: 'Charlie Breezy',
    level: 'all',
    category: 'urbano',
    link: '/clases/reggaeton-cubano-barcelona',
  },
  {
    id: 'tue-7',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana Básico I',
    day: 'tuesday',
    time: '20:00',
    teacher: 'Yunaisy Farray',
    level: 'basic',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'tue-8',
    styleName: 'Sexy Reggaeton',
    className: 'Sexy Reggaeton',
    day: 'tuesday',
    time: '20:00',
    teacher: 'Yasmina Fernández',
    level: 'basic',
    category: 'urbano',
    link: '/clases/sexy-reggaeton-barcelona',
  },
  {
    id: 'tue-9',
    styleName: 'Femmology',
    className: 'Femmology',
    day: 'tuesday',
    time: '20:30',
    teacher: 'Yunaisy Farray',
    level: 'intermediate',
    category: 'urbano',
    link: '/clases/femmology-barcelona',
  },
  {
    id: 'tue-10',
    styleName: 'Timba',
    className: 'Timba en Pareja',
    day: 'tuesday',
    time: '20:30',
    teacher: 'Grechén Mendez',
    level: 'basic',
    category: 'latino',
    link: '/clases/timba-barcelona',
  },
  {
    id: 'tue-11',
    styleName: 'Folklore Cubano',
    className: 'Folklore Cubano',
    day: 'tuesday',
    time: '20:30',
    teacher: 'Grechén Mendez',
    level: 'all',
    category: 'latino',
    link: '/clases/folklore-cubano-barcelona',
  },
  {
    id: 'tue-12',
    styleName: 'Sexy Style',
    className: 'Sexy Style',
    day: 'tuesday',
    time: '21:00',
    teacher: 'Yasmina Fernández',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/sexy-style-barcelona',
  },
  {
    id: 'tue-13',
    styleName: 'Femmology',
    className: 'Femmology',
    day: 'tuesday',
    time: '21:30',
    teacher: 'Yunaisy Farray',
    level: 'advanced',
    category: 'urbano',
    link: '/clases/femmology-barcelona',
  },
  {
    id: 'tue-14',
    styleName: 'Twerk',
    className: 'Twerk',
    day: 'tuesday',
    time: '22:00',
    teacher: 'Sandra Gómez',
    level: 'basic',
    category: 'urbano',
    link: '/clases/twerk-barcelona',
  },

  // ========== WEDNESDAY ==========
  {
    id: 'wed-1',
    styleName: 'Contemporáneo',
    className: 'Contemporáneo Suelo & Flow',
    day: 'wednesday',
    time: '11:00',
    teacher: 'Alejandro Miñoso',
    level: 'intermediate',
    category: 'danza',
    link: '/clases/contemporaneo-barcelona',
  },
  {
    id: 'wed-2',
    styleName: 'Afro Jazz',
    className: 'Afro Jazz',
    day: 'wednesday',
    time: '12:00',
    teacher: 'Alejandro Miñoso',
    level: 'basic',
    category: 'danza',
    link: '/clases/afro-jazz-barcelona',
  },
  {
    id: 'wed-3',
    styleName: 'Stretching',
    className: 'Stretching',
    day: 'wednesday',
    time: '18:00',
    teacher: 'Cris Ag',
    level: 'beginner',
    category: 'fitness',
    link: '/clases/stretching-barcelona',
  },
  {
    id: 'wed-4',
    styleName: 'Contemporáneo',
    className: 'Contemporáneo Suelo & Flow',
    day: 'wednesday',
    time: '18:00',
    teacher: 'Alejandro Miñoso',
    level: 'intermediate',
    category: 'danza',
    link: '/clases/contemporaneo-barcelona',
  },
  {
    id: 'wed-5',
    styleName: 'Hip Hop Reggaeton',
    className: 'Hip Hop Reggaeton',
    day: 'wednesday',
    time: '18:00',
    teacher: 'Charlie Breezy',
    level: 'basic',
    category: 'urbano',
    link: '/clases/hip-hop-reggaeton-barcelona',
  },
  {
    id: 'wed-6',
    styleName: 'Bum Bum Glúteos',
    className: 'Bum Bum Glúteos',
    day: 'wednesday',
    time: '19:00',
    teacher: 'Cris Ag',
    level: 'all',
    category: 'fitness',
    link: '/clases/bum-bum-gluteos-barcelona',
  },
  {
    id: 'wed-7',
    styleName: 'Salsa Lady Style',
    className: 'Salsa Lady Style',
    day: 'wednesday',
    time: '19:00',
    teacher: 'Yunaisy Farray',
    level: 'intermediate',
    category: 'latino',
    link: '/clases/salsa-lady-style-barcelona',
  },
  {
    id: 'wed-8',
    styleName: 'Hip Hop Reggaeton',
    className: 'Hip Hop Reggaeton',
    day: 'wednesday',
    time: '19:00',
    teacher: 'Charlie Breezy',
    level: 'intermediateAdvanced',
    category: 'urbano',
    link: '/clases/hip-hop-reggaeton-barcelona',
  },
  {
    id: 'wed-9',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana Básico II-III',
    day: 'wednesday',
    time: '20:00',
    teacher: 'Yunaisy Farray',
    level: 'basic',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'wed-10',
    styleName: 'Contemporáneo',
    className: 'Contemporáneo Lírico',
    day: 'wednesday',
    time: '20:00',
    teacher: 'Daniel Sené',
    level: 'intermediate',
    category: 'danza',
    link: '/clases/contemporaneo-barcelona',
  },
  {
    id: 'wed-11',
    styleName: 'Stretching',
    className: 'Backbending & Legs',
    day: 'wednesday',
    time: '20:00',
    teacher: 'Cris Ag',
    level: 'intermediate',
    category: 'fitness',
    link: '/clases/stretching-barcelona',
  },
  {
    id: 'wed-12',
    styleName: 'Femmology',
    className: 'Femmology',
    day: 'wednesday',
    time: '21:00',
    teacher: 'Yunaisy Farray',
    level: 'basic',
    category: 'urbano',
    link: '/clases/femmology-barcelona',
  },
  {
    id: 'wed-13',
    styleName: 'Dancehall',
    className: 'Dancehall Twerk',
    day: 'wednesday',
    time: '21:00',
    teacher: 'Isabel López',
    level: 'intermediate',
    category: 'urbano',
    link: '/clases/dancehall-barcelona',
  },
  {
    id: 'wed-14',
    styleName: 'Twerk',
    className: 'Twerk',
    day: 'wednesday',
    time: '22:00',
    teacher: 'Sandra Gómez',
    level: 'intermediate',
    category: 'urbano',
    link: '/clases/twerk-barcelona',
  },

  // ========== THURSDAY ==========
  {
    id: 'thu-1',
    styleName: 'Reggaeton Cubano',
    className: 'Reggaeton Cubano',
    day: 'thursday',
    time: '10:00',
    teacher: 'Alejandro Miñoso',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/reggaeton-cubano-barcelona',
  },
  {
    id: 'thu-2',
    styleName: 'Sexy Reggaeton',
    className: 'Sexy Reggaeton',
    day: 'thursday',
    time: '10:00',
    teacher: 'Yasmina Fernández',
    level: 'basic',
    category: 'urbano',
    link: '/clases/sexy-reggaeton-barcelona',
  },
  {
    id: 'thu-3',
    styleName: 'Ballet',
    className: 'Ballet',
    day: 'thursday',
    time: '11:00',
    teacher: 'Alejandro Miñoso',
    level: 'basic',
    category: 'danza',
    link: '/clases/ballet-barcelona',
  },
  {
    id: 'thu-4',
    styleName: 'Sexy Style',
    className: 'Sexy Style',
    day: 'thursday',
    time: '11:00',
    teacher: 'Yasmina Fernández',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/sexy-style-barcelona',
  },
  {
    id: 'thu-5',
    styleName: 'Contemporáneo',
    className: 'Contemporáneo Lírico',
    day: 'thursday',
    time: '18:00',
    teacher: 'Daniel Sené',
    level: 'basic',
    category: 'danza',
    link: '/clases/contemporaneo-barcelona',
  },
  {
    id: 'thu-6',
    styleName: 'Stretching',
    className: 'Stretching',
    day: 'thursday',
    time: '19:00',
    teacher: 'Daniel Sené',
    level: 'basic',
    category: 'fitness',
    link: '/clases/stretching-barcelona',
  },
  {
    id: 'thu-7',
    styleName: 'Afro Jazz',
    className: 'Afro Jazz',
    day: 'thursday',
    time: '19:00',
    teacher: 'Yunaisy Farray',
    level: 'intermediateAdvanced',
    category: 'danza',
    link: '/clases/afro-jazz-barcelona',
  },
  {
    id: 'thu-8',
    styleName: 'Sexy Reggaeton',
    className: 'Sexy Reggaeton',
    day: 'thursday',
    time: '19:00',
    teacher: 'Yasmina Fernández',
    level: 'intermediate',
    category: 'urbano',
    link: '/clases/sexy-reggaeton-barcelona',
  },
  {
    id: 'thu-9',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana',
    day: 'thursday',
    time: '20:00',
    teacher: 'Yunaisy Farray',
    level: 'intermediate',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
  {
    id: 'thu-10',
    styleName: 'Hip Hop',
    className: 'Hip Hop Urbano',
    day: 'thursday',
    time: '20:00',
    teacher: 'Marcos Martínez',
    level: 'all',
    category: 'urbano',
    link: '/clases/hip-hop-barcelona',
  },
  {
    id: 'thu-11',
    styleName: 'Timba',
    className: 'Lady Timba',
    day: 'thursday',
    time: '20:30',
    teacher: 'Yunaisy Farray',
    level: 'intermediateAdvanced',
    category: 'latino',
    link: '/clases/timba-barcelona',
  },
  {
    id: 'thu-12',
    styleName: 'Dancehall',
    className: 'Dancehall Female',
    day: 'thursday',
    time: '21:00',
    teacher: 'Isabel López',
    level: 'advanced',
    category: 'urbano',
    link: '/clases/dancehall-barcelona',
  },
  {
    id: 'thu-13',
    styleName: 'Sexy Style',
    className: 'Sexy Style',
    day: 'thursday',
    time: '21:00',
    teacher: 'Yasmina Fernández',
    level: 'intermediate',
    category: 'urbano',
    link: '/clases/sexy-style-barcelona',
  },
  {
    id: 'thu-14',
    styleName: 'Femmology',
    className: 'Femmology',
    day: 'thursday',
    time: '21:30',
    teacher: 'Yunaisy Farray',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/femmology-barcelona',
  },
  {
    id: 'thu-15',
    styleName: 'Dancehall',
    className: 'Dancehall Female',
    day: 'thursday',
    time: '22:00',
    teacher: 'Sandra Gómez',
    level: 'basic',
    category: 'urbano',
    link: '/clases/dancehall-barcelona',
  },

  // ========== FRIDAY ==========
  {
    id: 'fri-1',
    styleName: 'Hip Hop Reggaeton',
    className: 'Hip Hop Reggaeton',
    day: 'friday',
    time: '18:00',
    teacher: 'Charlie Breezy',
    level: 'basic',
    category: 'urbano',
    link: '/clases/hip-hop-reggaeton-barcelona',
  },
  {
    id: 'fri-2',
    styleName: 'Afrobeat',
    className: 'Afrobeat',
    day: 'friday',
    time: '18:00',
    teacher: 'Charlie Breezy',
    level: 'basic',
    category: 'urbano',
    link: '/clases/afrobeat-barcelona',
  },
  {
    id: 'fri-3',
    styleName: 'Dancehall',
    className: 'Dancehall Twerk',
    day: 'friday',
    time: '18:00',
    teacher: 'Isabel López',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/dancehall-barcelona',
  },
  {
    id: 'fri-4',
    styleName: 'Twerk',
    className: 'Twerk',
    day: 'friday',
    time: '19:00',
    teacher: 'Isabel López',
    level: 'beginner',
    category: 'urbano',
    link: '/clases/twerk-barcelona',
  },
  {
    id: 'fri-5',
    styleName: 'Salsa Lady Style',
    className: 'Salsa Lady Style',
    day: 'friday',
    time: '19:00',
    teacher: 'Yunaisy Farray',
    level: 'advanced',
    category: 'latino',
    link: '/clases/salsa-lady-style-barcelona',
  },
  {
    id: 'fri-6',
    styleName: 'Timba',
    className: 'Lady Timba',
    day: 'friday',
    time: '19:00',
    teacher: 'Lia Valdés',
    level: 'basic',
    category: 'latino',
    link: '/clases/timba-barcelona',
  },
  {
    id: 'fri-7',
    styleName: 'Salsa Cubana',
    className: 'Salsa Cubana',
    day: 'friday',
    time: '20:00',
    teacher: 'Yunaisy Farray',
    level: 'advanced',
    category: 'latino',
    link: '/clases/salsa-cubana-barcelona',
  },
];

// Helper function to get classes by day
export const getClassesByDay = (day: DayKey): ScheduleClass[] => {
  return SCHEDULE_DATA.filter(c => c.day === day).sort((a, b) => a.time.localeCompare(b.time));
};

// Helper function to get classes by category
export const getClassesByCategory = (category: CategoryKey): ScheduleClass[] => {
  return SCHEDULE_DATA.filter(c => c.category === category);
};

// Helper function to filter classes
export const filterClasses = (
  day: DayKey | 'all',
  category: CategoryKey | 'all'
): ScheduleClass[] => {
  let filtered = [...SCHEDULE_DATA];

  if (day !== 'all') {
    filtered = filtered.filter(c => c.day === day);
  }

  if (category !== 'all') {
    filtered = filtered.filter(c => c.category === category);
  }

  return filtered.sort((a, b) => {
    // Sort by day first, then by time
    const dayDiff = DAY_ORDER.indexOf(a.day) - DAY_ORDER.indexOf(b.day);
    if (dayDiff !== 0) return dayDiff;
    return a.time.localeCompare(b.time);
  });
};

// Get unique teachers
export const getUniqueTeachers = (): string[] => {
  return [...new Set(SCHEDULE_DATA.map(c => c.teacher))].sort();
};

// Get class count by category
export const getCountByCategory = (): Record<CategoryKey | 'all', number> => {
  return {
    all: SCHEDULE_DATA.length,
    latino: getClassesByCategory('latino').length,
    urbano: getClassesByCategory('urbano').length,
    danza: getClassesByCategory('danza').length,
    fitness: getClassesByCategory('fitness').length,
  };
};
