// Auto-generated LQIP placeholders for schedule images
// Generated by scripts/optimize-schedule-images.mjs
// Do not edit manually

export const SCHEDULE_BLUR_PLACEHOLDERS = {
  danza:
    'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAgCdASoUAA8APzmGuVO0qSWkMAgCkCcJQBWABckgAP7sfVxc3stOamdZYWAAAAA=',
  morning:
    'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAgCdASoUAA8APzmGulQvKSWjMAgB4CcJZQCnFC5JAAD+6YixewygvgmLvBJMpYAAAA==',
  social:
    'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAgCdASoUAA8APzmEuVOvKKWisAgB4CcJYwCsADDWAAD+6nPKiRyQ6gCtEXQogE6AAAAA',
  urban:
    'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAgCdASoUAA8APzmEuVO0qKWisAgCkCcJZwDImC5JAAD+7NUoq3S4MEO2K7DfgAA=',
};
